import { HIDDEN_LOGO_URL, HIDDEN_QR_URL, HIDDEN_WEB_URL, PDF_MARGIN_MM } from './constants';

export type PdfLanguage = 'es' | 'en';

export function escapeHtml(value: unknown): string {
    return String(value ?? '')
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;');
}

const COPY = {
    es: {
        generatedBy: 'Generado por Hidden App',
        scanQr: 'Escanea el QR para visitar hiddenapp.co',
        websiteLabel: 'hiddenapp.co',
    },
    en: {
        generatedBy: 'Generated by Hidden App',
        scanQr: 'Scan the QR to visit hiddenapp.co',
        websiteLabel: 'hiddenapp.co',
    },
} as const;

export function pdfBaseStyles(): string {
    return `
        @page {
            size: A4 portrait;
            margin: 0;
        }

        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
        }

        html, body {
            margin: 0;
            padding: 0;
            width: 100%;
            min-height: 100%;
            font-family: 'Outfit', -apple-system, sans-serif;
            background: #020710;
            color: #fff;
        }

        .pdf-doc {
            width: 100%;
            min-height: 100%;
            background: #020710;
            position: relative;
        }

        .content {
            position: relative;
            z-index: 1;
            width: 100%;
            padding: ${PDF_MARGIN_MM.top} ${PDF_MARGIN_MM.right} ${PDF_MARGIN_MM.bottom} ${PDF_MARGIN_MM.left};
        }

        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding-bottom: 18px;
            border-bottom: 1px solid rgba(255,255,255,0.06);
            margin-bottom: 28px;
            break-after: avoid;
        }
        .logo-img { height: 32px; width: auto; display: block; }
        .header-badge {
            background: rgba(255,108,82,0.1);
            border: 1px solid rgba(255,108,82,0.22);
            color: #ff6c52;
            padding: 5px 12px;
            border-radius: 100px;
            font-size: 8px;
            font-weight: 800;
            letter-spacing: 0.04em;
            text-transform: uppercase;
            white-space: nowrap;
            max-width: 42%;
            overflow: hidden;
            text-overflow: ellipsis;
        }

        .hero-title {
            font-size: 34px;
            font-weight: 900;
            line-height: 1.1;
            letter-spacing: -0.03em;
            margin-bottom: 8px;
            color: #f1f5f9;
            word-wrap: break-word;
        }
        .hero-sub {
            font-size: 10px;
            font-weight: 700;
            color: #ff6c52;
            text-transform: uppercase;
            letter-spacing: 0.06em;
            margin-bottom: 8px;
        }
        .hero-meta {
            font-size: 12px;
            color: #64748b;
            font-weight: 500;
            margin-bottom: 24px;
            line-height: 1.5;
        }

        .section-title {
            font-size: 13px;
            font-weight: 800;
            color: #fff;
            margin: 22px 0 12px;
            padding-bottom: 8px;
            border-bottom: 1px solid rgba(255,255,255,0.06);
            display: flex;
            align-items: center;
            gap: 8px;
            break-after: avoid;
        }
        .section-title::before {
            content: '';
            width: 3px;
            height: 13px;
            background: #ff6c52;
            border-radius: 2px;
            flex-shrink: 0;
        }

        .prose {
            font-size: 11.5px;
            line-height: 1.62;
            color: #cbd5e1;
            font-weight: 450;
            word-wrap: break-word;
            hyphens: auto;
        }

        .card {
            background: rgba(255,255,255,0.025);
            border: 1px solid rgba(255,255,255,0.06);
            border-radius: 14px;
            padding: 14px 16px;
            margin-bottom: 10px;
            break-inside: avoid;
        }
        .card-compact { break-inside: avoid; }

        .card-label {
            font-size: 8.5px;
            font-weight: 800;
            color: #64748b;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            margin-bottom: 5px;
        }
        .card-value {
            font-size: 12.5px;
            font-weight: 600;
            color: #e2e8f0;
            line-height: 1.5;
            word-wrap: break-word;
        }

        .list { list-style: none; padding: 0; margin: 0; }
        .list li {
            font-size: 11.5px;
            color: #cbd5e1;
            padding: 7px 0;
            border-bottom: 1px solid rgba(255,255,255,0.04);
            display: flex;
            gap: 10px;
            align-items: flex-start;
        }
        .list li:last-child { border-bottom: none; }
        .bullet {
            width: 5px;
            height: 5px;
            border-radius: 50%;
            background: #ff6c52;
            margin-top: 6px;
            flex-shrink: 0;
        }

        .tip-box {
            background: linear-gradient(135deg, rgba(255,108,82,0.08), rgba(255,108,82,0.02));
            border: 1px solid rgba(255,108,82,0.15);
            border-radius: 12px;
            padding: 14px 16px;
            margin-top: 8px;
            break-inside: avoid;
        }
        .tip-label {
            font-size: 8.5px;
            font-weight: 800;
            color: #ff6c52;
            letter-spacing: 0.05em;
            text-transform: uppercase;
            margin-bottom: 6px;
        }

        .day-block {
            margin-bottom: 22px;
            padding-bottom: 4px;
        }
        .day-block + .day-block {
            padding-top: 4px;
        }

        .footer {
            margin-top: 32px;
            padding-top: 18px;
            border-top: 1px solid rgba(255,255,255,0.06);
            display: flex;
            justify-content: space-between;
            align-items: flex-end;
            gap: 16px;
            break-inside: avoid;
        }
        .footer-qr { width: 48px; height: 48px; border-radius: 6px; flex-shrink: 0; }
        .footer-text { font-size: 9.5px; color: #475569; font-weight: 600; line-height: 1.45; }
        .footer-accent { color: #ff6c52; font-weight: 800; }
        .footer-link {
            color: #ff6c52;
            font-weight: 700;
            text-decoration: none;
            font-size: 9.5px;
            display: block;
            margin-top: 2px;
        }
        .seal-lines { text-align: right; flex-shrink: 0; }
        .seal-line {
            font-size: 8px;
            font-weight: 700;
            color: #334155;
            text-transform: uppercase;
            letter-spacing: 0.06em;
        }
        .seal-line.accent { color: #ff6c52; }

        .price-row {
            display: flex;
            justify-content: space-between;
            gap: 12px;
            font-size: 11px;
            color: #cbd5e1;
            padding: 5px 0;
            border-bottom: 1px solid rgba(255,255,255,0.04);
            word-wrap: break-word;
        }
        .price-row strong { color: #fff; font-weight: 700; flex-shrink: 0; }

        .hero-image {
            width: 100%;
            max-height: 180px;
            object-fit: cover;
            border-radius: 14px;
            margin-bottom: 16px;
            border: 1px solid rgba(255,255,255,0.08);
            display: block;
            break-inside: avoid;
        }

        .budget-card {
            background: linear-gradient(135deg, rgba(34,197,94,0.08), transparent);
            border-color: rgba(34,197,94,0.2);
            break-inside: avoid;
            margin-bottom: 20px;
        }
        .budget-amount {
            font-size: 20px;
            font-weight: 900;
            color: #4ade80;
            line-height: 1.2;
            margin-top: 4px;
        }
    `;
}

/** Shared hero block styles — used by expedition and destination PDFs. */
export function pdfHeroStyles(): string {
    return `
        .pdf-hero {
            margin-bottom: 22px;
            padding-bottom: 18px;
            border-bottom: 1px solid rgba(255,255,255,0.06);
            break-inside: avoid;
        }
        .pdf-meta-row {
            display: flex;
            flex-wrap: wrap;
            gap: 6px;
            margin-bottom: 14px;
        }
        .meta-pill {
            display: inline-block;
            font-size: 8.5px;
            font-weight: 800;
            letter-spacing: 0.04em;
            text-transform: uppercase;
            color: #94a3b8;
            background: rgba(255,255,255,0.04);
            border: 1px solid rgba(255,255,255,0.08);
            border-radius: 999px;
            padding: 4px 10px;
            line-height: 1.3;
        }
        .meta-pill.accent {
            color: #ff8a75;
            background: rgba(255,108,82,0.12);
            border-color: rgba(255,108,82,0.28);
        }
        .pdf-hero-title {
            font-size: 28px;
            font-weight: 900;
            line-height: 1.15;
            letter-spacing: -0.025em;
            color: #f1f5f9;
            margin-bottom: 0;
            word-wrap: break-word;
            hyphens: auto;
        }
        .pdf-hero-lead {
            font-size: 11.5px;
            line-height: 1.65;
            color: #94a3b8;
            font-weight: 450;
            margin-top: 12px;
            word-wrap: break-word;
            hyphens: auto;
        }
    `;
}

export function pdfHeader(badge: string): string {
    return `
        <div class="header">
            <img src="${HIDDEN_LOGO_URL}" class="logo-img" alt="Hidden" />
            <div class="header-badge">${escapeHtml(badge)}</div>
        </div>
    `;
}

export function pdfFooter(lang: PdfLanguage, sealLine1: string, sealLine2: string): string {
    const c = COPY[lang];
    return `
        <div class="footer">
            <div style="display:flex;gap:10px;align-items:flex-start;min-width:0;">
                <img src="${HIDDEN_QR_URL}" class="footer-qr" alt="QR" />
                <div style="min-width:0;">
                    <div class="footer-text">${escapeHtml(c.generatedBy)}</div>
                    <div class="footer-text footer-accent">${escapeHtml(c.scanQr)}</div>
                    <a class="footer-link" href="${HIDDEN_WEB_URL}">${escapeHtml(c.websiteLabel)}</a>
                </div>
            </div>
            <div class="seal-lines">
                <div class="seal-line">${escapeHtml(sealLine1)}</div>
                <div class="seal-line accent">${escapeHtml(sealLine2)}</div>
            </div>
        </div>
    `;
}

export function wrapPdfDocument(
    title: string,
    lang: PdfLanguage,
    bodyInner: string,
    additionalStyles = ''
): string {
    return `<!DOCTYPE html>
<html lang="${lang}">
<head>
    <meta charset="UTF-8" />
    <title>${escapeHtml(title)}</title>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@400;500;600;700;800;900&display=swap" rel="stylesheet" />
    <style>${pdfBaseStyles()}${additionalStyles}</style>
</head>
<body>
    <div class="pdf-doc">
        <div class="content">${bodyInner}</div>
    </div>
</body>
</html>`;
}
